apiVersion: v1
kind: Pod
metadata:
  name: $POD_NAME
  namespace: $NAMESPACE
  annotations:
    cni.projectcalico.org/ipAddrs: '["$POD_IP"]'
spec:
  containers:
    - name: $POD_NAME
      image: $IMAGE
      ports:
        - containerPort: $PORT
