apiVersion: v1
kind: Pod
metadata:
  name: created-pod-1
  namespace: test-namespace
  annotations:
    cni.projectcalico.org/ipAddrs: '["192.168.120.65"]'
spec:
  containers:
    - name: created-pod-1
      image: nginx:1.14.2
      ports:
        - containerPort: 8081
